### ISSUE TITLE
能否写一下安装运行步骤？

### ISSUE THREAD

**Issue by JorsunZhao** [liunian1004/goes#1]
go刚入门，想学习iris框架，看到您的项目，按照自己理解运行（前端）没成功，能否写下安装运行步骤？拜谢~

**Comment by JorsunZhao** [comment]
$ npm run dev

> web@1.0.0 dev C:\Users\18622\go\src\github.com\goes\web
> nuxt

2018-06-28T02:59:00.886Z nuxt:build App root: C:\Users\18622\go\src\github.com\goes\web
2018-06-28T02:59:00.887Z nuxt:build Generating C:\Users\18622\go\src\github.com\goes\web\.nuxt files...
2018-06-28T02:59:00.901Z nuxt:build Generating files...
2018-06-28T02:59:00.905Z nuxt:build Generating routes...
2018-06-28T02:59:00.971Z nuxt:build Building files...
2018-06-28T02:59:01.078Z nuxt:build Adding webpack middleware...
 ERROR  Failed to compile with 1 errors10:59:05

This dependency was not found:

* assets/images/logo.png in ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-46cf1d15","hasScoped":false,"preserveWhitespace":false,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0&bustCache!./components/Header.vue

To install it, you can run: npm install --save assets/images/logo.png
Error: listen EADDRINUSE 127.0.0.1:3000
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web@1.0.0 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\18622\AppData\Roaming\npm-cache\_logs\2018-06-28T02_59_05_969Z-debug.log

**Comment by aizk** [comment]
刚入门你可以看看 go web编程这本书，理解 go 开发 web 程序的核心，各类框架其实都一样，这个项目只是实验性产品，目前我已经采用 echo 开发后端服务了，这个框架符合我的简单易用标准。谢谢

**Comment by JorsunZhao** [comment]
好的，谢谢
